apiVersion: v1
kind: ServiceAccount
metadata:
  name: vertex-agent-ksa
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: vertex-gke-agent@seir-1-490120.iam.gserviceaccount.com

    # Replace: PROJECT_ID with your project ID i.e. lizzo-lover-039494